app/utils/ViewUtils.scala, project/AppDependencies.scala, test/utils/ViewUtilSpec.scala
Update displayed currency values to match GDS way
[SASS-1480](https://jira.tools.tax.service.gov.uk/browse/SASS-1480)
=> Display Currency in correct format

app/models/AllCISDeductions.scala, app/models/CISSource.scala, app/models/CisDeductions.scala, app/models/GetPeriodData.scala, app/models/mongo/CYAPeriodData.scala, app/models/mongo/CisCYAModel.scala, app/models/mongo/CisUserData.scala, app/services/EncryptionService.scala, app/utils/MonthEnums.scala, it/connectors/IncomeTaxUserDataConnectorSpec.scala, it/repositories/CisUserDataRepositoryISpec.scala, it/services/EncryptionServiceTest.scala, it/utils/IntegrationTest.scala, test/builders/models/AllCISDeductionsBuilder.scala, test/builders/models/CISSourceBuilder.scala, test/builders/models/CisDeductionsBuilder.scala, test/builders/models/GetPeriodDataBuilder.scala, test/builders/models/IncomeTaxUserDataBuilder.scala, test/builders/models/UserBuilder.scala, test/builders/models/mongo/CYAPeriodDataBuilder.scala, test/builders/models/mongo/CisCYAModelBuilder.scala, test/builders/models/mongo/CisUserDataBuilder.scala, test/forms/FormUtilsSpec.scala, test/forms/testUtils/StringContraintsSpec.scala, test/models/CYAPeriodDataSpec.scala, test/models/CisCYAModelSpec.scala, test/utils/MonthEnumsSpec.scala, test/utils/UnitTest.scala
- added CIS models and mongo models (CYA, user data model)
- added builder models for tests
[SASS-2179](https://jira.tools.tax.service.gov.uk/browse/SASS-2179)
=> SASS 2179 - Set up CIS Model

app/connectors/IncomeTaxUserDataConnector.scala, app/connectors/parsers/IncomeTaxUserDataHttpParser.scala, app/controllers/DeductionsSummaryController.scala, app/services/DeductionsSummaryService.scala
=> [TEMP] Adding logs temprorarily for debug purposes.

app/connectors/IncomeTaxUserDataConnector.scala, app/connectors/parsers/IncomeTaxUserDataHttpParser.scala, app/controllers/DeductionsSummaryController.scala, app/services/DeductionsSummaryService.scala
This reverts commit 28380517c57ffbeaceb9fee3aa7dfec26c990552.
=> Revert "[TEMP] Adding logs temprorarily for debug purposes."

app/repositories/CisUserDataRepositoryImpl.scala, app/utils/StartUpLogging.scala, conf/application-json-logger.xml
=> SASS-2436C Added log indexes method and replacing indexes

app/views/DeductionsSummaryView.scala.html, test/views/DeductionsSummaryViewSpec.scala
Added functionality to Return to Overview button in CIS Deductions page. It will now redirect the user to Your Income Tax Return page.
[SASS-2175](https://jira.tools.tax.service.gov.uk/browse/SASS-2175)
=> SASS-2175 - Added navigation to Return to Overview button

project/AppDependencies.scala
Updating dependencies
[SASS-2548](https://jira.tools.tax.service.gov.uk/browse/SASS-2009)
=> [DM] [SASS-2548] Updating dependencies

app/assets/stylesheets/application.scss
[SASS-2332](https://jira.tools.tax.service.gov.uk/browse/SASS-2332)
=> [SASS-2332] Back link and language toggle layout

app/assets/stylesheets/itsa-print.css, app/views/templates/Head.scala.html, app/views/templates/Layout.scala.html, project/AppDependencies.scala
SASS-2523 fix to print preview styling.
[SASS-2523](https://jira.tools.tax.service.gov.uk/browse/SASS-2523)
=> SASS-2523 print preview styling

app/controllers/ContractorDetailsController.scala, app/forms/ContractorDetailsForm.scala, app/models/pages/ContractorDetailsViewModel.scala, app/repositories/CisUserDataRepositoryImpl.scala, app/services/ContractorDetailsService.scala, app/views/ContractorDetailsView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/ContractorDetailsControllerISpec.scala, it/repositories/CisUserDataRepositoryISpec.scala, test/controllers/ContractorDetailsControllerSpec.scala, test/forms/ContractorDetailsFormSpec.scala, test/models/ContractorDetailsViewModelSpec.scala, test/services/ContractorDetailsServiceSpec.scala, test/support/mocks/MockContractorDetailsService.scala, test/views/ContractorDetailsViewSpec.scala
Created CIS contractor details EOY page
[SASS-2169](https://jira.tools.tax.service.gov.uk/browse/SASS-2169)
=> SASS-2169 Create CIS contractor details EOY page

it/controllers/SessionExpiredControllerISpec.scala, it/support/IntegrationTest.scala, test/config/MockAppConfig.scala, test/support/TaxYearHelper.scala, test/support/builders/models/mongo/CisUserDataBuilder.scala, test/views/DeductionPeriodViewSpec.scala
[SASS-2663](https://jira.tools.tax.service.gov.uk/browse/SASS-2663)
=> [SASS-2663] intergrationTest dynamic taxYear

conf/messages, conf/messages.cy, test/views/MaterialsViewSpec.scala
[SASS-2173](https://jira.tools.tax.service.gov.uk/browse/SASS-2173)
=> SASS-2173 - [Fix] Uses correct opening quote.

app/controllers/ContractorDetailsController.scala, app/controllers/DeductionAmountController.scala, app/controllers/DeductionsSummaryController.scala, app/controllers/LabourPayController.scala, app/controllers/MaterialsAmountController.scala, app/controllers/MaterialsController.scala, app/forms/FormsProvider.scala, app/models/pages/MaterialsAmountPage.scala, app/services/DeductionAmountService.scala, app/services/MaterialsService.scala, app/views/DeductionAmountView.scala.html, app/views/MaterialsAmountView.scala.html, app/views/templates/helpers/InputTextAlt.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/controllers/MaterialsAmountControllerISpec.scala, it/controllers/MaterialsControllerISpec.scala, test/controllers/DeductionAmountControllerSpec.scala, test/controllers/MaterialsAmountControllerSpec.scala, test/controllers/MaterialsControllerSpec.scala, test/forms/FormsProviderSpec.scala, test/models/pages/MaterialsAmountPageSpec.scala, test/services/DeductionAmountServiceSpec.scala, test/services/MaterialsServiceSpec.scala, test/support/builders/models/pages/MaterialsAmountPageBuilder.scala, test/support/mocks/MockActionsProvider.scala, test/support/mocks/MockDeductionAmountService.scala, test/support/mocks/MockMaterialsService.scala, test/views/MaterialsAmountViewSpec.scala
[SASS-2174](https://jira.tools.tax.service.gov.uk/browse/SASS-2174)
=> SASS-2174 - Create CIS materials amount EOY page.

test/utils/TaxYearUtils.scala
=> SASS-2720 - [Fix] Fixes TaxYearUtils.

app/actions/ActionsProvider.scala, app/actions/AuthorisedAction.scala, app/actions/HasInYearCisDeductionsActionFilter.scala, app/actions/HasInYearDeductionsForEmployerRefAndMonthActionFilter.scala, app/actions/HasInYearPeriodDataWithEmployerRefActionFilter.scala, app/controllers/ContractorCYAController.scala, app/controllers/ContractorSummaryController.scala, app/controllers/DeductionAmountController.scala, app/controllers/DeductionsSummaryController.scala, app/controllers/LabourPayController.scala, app/controllers/MaterialsAmountController.scala, app/controllers/MaterialsController.scala, app/controllers/SignOutController.scala, app/forms/FormsProvider.scala, app/models/pages/DeductionAmountPage.scala, app/models/pages/LabourPayPage.scala, app/models/pages/MaterialsAmountPage.scala, app/models/pages/MaterialsPage.scala, app/repositories/CisUserDataRepositoryImpl.scala, app/services/CISSessionService.scala, app/views/templates/AgentAuthErrorPageView.scala.html, app/views/templates/IndividualUnauthorisedView.scala.html, app/views/templates/InternalServerErrorTemplate.scala.html, app/views/templates/NotFoundTemplate.scala.html, app/views/templates/ServiceUnavailableTemplate.scala.html, app/views/templates/TaxYearErrorTemplate.scala.html, app/views/templates/TimeoutPage.scala.html, app/views/templates/UnauthorisedUserErrorPageView.scala.html, app/views/templates/YouNeedAgentServicesView.scala.html
=> Refactoring

app/views/ContractorSummaryView.scala.html, conf/messages, conf/messages.cy, test/views/ContractorSummaryViewSpec.scala
[SASS-2085](https://jira.tools.tax.service.gov.uk/browse/SASS-2085)
=> SASS-2085 - Agent inset text added.

app/actions/ActionsProvider.scala, app/actions/TaxYearAction.scala, app/common/SessionValues.scala, app/controllers/errors/TaxYearErrorController.scala, app/utils/TaxYearHelper.scala, app/views/templates/TaxYearErrorTemplate.scala.html, conf/messages, conf/messages.cy, it/controllers/errors/TaxYearErrorControllerISpec.scala, it/support/IntegrationTest.scala, project/AppDependencies.scala, test/actions/ActionsProviderSpec.scala, test/actions/TaxYearActionSpec.scala, test/controllers/errors/TaxYearErrorControllerSpec.scala, test/support/TaxYearProvider.scala
Update the actions code in `income-tax-cis-frontend` to check for valid tax years defined in session.
[SASS-2731](https://jira.tools.tax.service.gov.uk/browse/SASS-2731)
=> SASS-2731: Update income-tax-cis-frontend to check for valid tax years in session

app/controllers/ContractorDetailsController.scala, app/forms/ContractorDetailsForm.scala, app/models/forms/ContractorDetails.scala, app/models/pages/ContractorDetailsPage.scala, app/services/ContractorDetailsService.scala, it/controllers/ContractorDetailsControllerISpec.scala, test/controllers/ContractorDetailsControllerSpec.scala, test/forms/ContractorDetailsFormSpec.scala, test/models/forms/ContractorDetailsSpec.scala, test/services/ContractorDetailsServiceSpec.scala, test/support/mocks/MockContractorDetailsService.scala, test/views/ContractorDetailsViewSpec.scala
[SASS-2176](https://jira.tools.tax.service.gov.uk/browse/SASS-2176)
=> SASS-2176 - [Fix] Fixes redirect when contractor data is updated.

app/actions/AuthorisedAction.scala, it/controllers/ContractorCYAControllerISpec.scala, it/helpers/WireMockHelper.scala, it/repositories/CisUserDataRepositoryISpec.scala, it/support/IntegrationTest.scala, project/AppDependencies.scala, test/actions/AuthorisedActionSpec.scala, test/actions/TaxYearActionSpec.scala, test/config/AppConfigSpec.scala, test/controllers/ContractorDetailsControllerSpec.scala, test/controllers/DeductionAmountControllerSpec.scala, test/controllers/DeductionPeriodControllerSpec.scala, test/controllers/LabourPayControllerSpec.scala, test/controllers/LanguageSwitchControllerSpec.scala, test/controllers/MaterialsAmountControllerSpec.scala, test/controllers/MaterialsControllerSpec.scala, test/controllers/errors/UnauthorisedUserErrorControllerSpec.scala, test/support/FakeRequestHelper.scala, test/support/ViewUnitTest.scala, test/support/builders/models/AuthorisationRequestBuilder.scala, test/support/mocks/MockActionsProvider.scala, test/utils/ViewTest.scala, test/views/ContractorCYAViewSpec.scala
[SASS-2842](https://jira.tools.tax.service.gov.uk/browse/SASS-2842)
=> SASS-2842 - Update CIS bootstrap-BE/FE-play-28 dependencies.

app/connectors/CISConnector.scala, app/connectors/parsers/CISHttpParser.scala, app/connectors/parsers/DeleteCISHttpParser.scala, app/services/DeleteCISPeriodService.scala, it/connectors/CISConnectorSpec.scala, it/connectors/NrsConnectorSpec.scala, it/controllers/DeleteCISPeriodControllerISpec.scala, it/helpers/WireMockHelper.scala, test/models/IncomeTaxUserDataSpec.scala, test/services/DeleteCISPeriodServiceSpec.scala, test/support/mocks/MockCISConnector.scala, test/utils/DateMonthUtilSpec.scala
https://jira.tools.tax.service.gov.uk/browse/SASS-2902
=> SASS-2990 FE DELETE Orchestration

app/actions/ActionsProvider.scala, app/actions/TailoringEnabledFilterAction.scala, app/config/AppConfig.scala, app/controllers/DeductionsFromPaymentsController.scala, app/forms/FormsProvider.scala, app/models/pages/DeductionsFromPaymentsPage.scala, app/views/DeductionsFromPaymentsView.scala.html, conf/app.routes, conf/application.conf, conf/messages, conf/messages.cy, it/controllers/DeductionsFromPaymentsControllerISpec.scala, test/actions/ActionsProviderSpec.scala, test/actions/TailoringEnabledFilterActionSpec.scala, test/config/MockAppConfig.scala, test/forms/FormsProviderSpec.scala, test/support/builders/models/pages/DeductionsFromPaymentsPageBuilder.scala, test/views/DeductionsFromPaymentsViewSpec.scala
Create CIS gateway page.
[SASS-2896](https://jira.tools.tax.service.gov.uk/browse/SASS-2896)
=> SASS-2896: CIS gateway page

app/actions/ActionsProvider.scala, app/actions/PriorViewCisPeriodNrsAction.scala, app/actions/SessionViewCisPeriodNrsAction.scala, app/models/nrs/AmendCisContractorPayload.scala, app/models/nrs/ContractorDetails.scala, app/models/nrs/CreateCisContractorPayload.scala, app/models/nrs/DeductionPeriod.scala, app/models/nrs/DeleteCisPeriodPayload.scala, app/models/nrs/NewCisContractor.scala, app/models/nrs/PreviousCisContractor.scala, app/models/nrs/ViewCisPeriodPayload.scala, app/services/ContractorCYAService.scala, app/services/DeleteCISPeriodService.scala, app/utils/JsonUtils.scala, project/AppDependencies.scala, test/actions/ActionsProviderSpec.scala, test/actions/PriorViewCisPeriodNrsActionSpec.scala, test/actions/SessionViewCisPeriodNrsActionSpec.scala, test/config/MockNrsService.scala, test/models/nrs/AmendCisContractorPayloadSpec.scala, test/models/nrs/CreateCisContractorPayloadSpec.scala, test/models/nrs/DeductionPeriodSpec.scala, test/models/nrs/DeleteCisPeriodPayloadSpec.scala, test/models/nrs/NewCisContractorSpec.scala, test/models/nrs/PreviousCisContractorSpec.scala, test/models/nrs/ViewCisPeriodPayloadSpec.scala, test/services/ContractorCYAServiceSpec.scala, test/services/DeleteCISPeriodServiceSpec.scala
[SASS-2280](https://jira.tools.tax.service.gov.uk/browse/SASS-2280)
=> SASS-2280 Submit CIS contractor view, creation, amend and deletion events to NRS

conf/messages, conf/messages.cy, test/views/MaterialsViewSpec.scala
[SASS-3054](https://jira.tools.tax.service.gov.uk/browse/SASS-3054)
=> SASS-3054: updated 'Pay for Materials' warning message

app/views/ContractorCYAView.scala.html, test/views/ContractorCYAViewSpec.scala
[SASS-3197](https://jira.tools.tax.service.gov.uk/browse/SASS-3197)
=> SASS-3197: CYA page paragraph text

app/actions/ActionsProvider.scala, app/actions/CisUserDataFinishedFilterAction.scala, app/actions/ViewCisPeriodAuditAction.scala, project/AppDependencies.scala, test/actions/ActionsProviderSpec.scala, test/actions/CisUserDataFinishedFilterActionSpec.scala, test/actions/ViewCisPeriodAuditActionSpec.scala, test/support/builders/models/nrs/ContractorDetailsBuilder.scala, test/support/builders/models/nrs/DeductionPeriodBuilder.scala, test/support/builders/models/nrs/ViewCisPeriodPayloadBuilder.scala
[SASS-3191](https://jira.tools.tax.service.gov.uk/browse/SASS-3191)
=> SASS-3191: Check your CIS deductions changes.

app/views/templates/Head.scala.html, app/views/templates/Layout.scala.html, conf/application.conf
[SASS-3689](https://jira.tools.tax.service.gov.uk/browse/SASS-3689)
=> SASS-3689 Set CSP policy configuration

project/AppDependencies.scala, test/support/builders/models/PeriodDataBuilder.scala
=> Upgrades  uk.gov.hmrc: play-frontend-hmrc.

project/AppDependencies.scala, project/plugins.sbt
=> Upgrade dependencies

app/views/templates/helpers/Heading.scala.html, test/support/ViewHelper.scala, test/views/DeductionAmountViewSpec.scala, test/views/DeductionsSummaryViewSpec.scala, test/views/DeleteCISPeriodViewSpec.scala, test/views/LabourPayViewSpec.scala, test/views/MaterialsAmountViewSpec.scala, test/views/templates/helpers/HeadingSpec.scala
[SASS-4234](https://jira.tools.tax.service.gov.uk/browse/SASS-4234)
=> SASS-4234 fix accessibility test issue - colour contrast

project/AppDependencies.scala, project/plugins.sbt
Upgrade Libraries in CIS FE
[SASS-4621](https://jira.tools.tax.service.gov.uk/browse/SASS-4621)
=> SASS-4621 Upgrade Libraries in CIS FE

conf/application.conf, it/connectors/IncomeTaxUserDataConnectorSpec.scala, it/controllers/ContractorCYAControllerISpec.scala, it/controllers/DeleteCISPeriodControllerISpec.scala, test/actions/CisUserDataFinishedFilterActionSpec.scala, test/audit/AmendCisContractorAuditSpec.scala, test/audit/CreateNewCisContractorAuditSpec.scala, test/audit/DeleteCisPeriodAuditSpec.scala, test/audit/ViewCisPeriodAuditSpec.scala, test/models/IncomeTaxUserDataSpec.scala, test/models/PeriodDataSpec.scala, test/models/mongo/CisUserDataSpec.scala, test/services/ContractorCYAServiceSpec.scala, test/support/builders/models/PeriodDataBuilder.scala, test/support/builders/models/submission/PeriodDataBuilder.scala
=> [NO-TICKET] Fix test failures caused by new tax year

app/views/MaterialsView.scala.html, conf/application.conf, project/AppDependencies.scala
[SASS-4853](https://jira.tools.tax.service.gov.uk/browse/SASS-4907)
=> SASS-4853:  X-XSS-Protection HTTP header is deprecated so disabling it

app/views/MaterialsView.scala.html
This fixes the following accessibility issue:
https://github.com/hmrc/accessibility-audits-external/issues/5752
[SASS-4903](https://jira.tools.tax.service.gov.uk/browse/SASS-4903)
=> SASS-4903 Remove hidden legend to fix accessibility issue

app/views/templates/helpers/InputText.scala.html
Removes the maxlength attribute from all text inputs 
Relevant story in Jira
[SASS-4901](https://jira.tools.tax.service.gov.uk/browse/SASS-4901)
=> SASS-4901: Remove the maxlength attribute from all text inputs and only perform server-side validation when the form is submitted

app/forms/ContractorDetailsForm.scala, app/forms/validation/mappings/MappingUtil.scala, test/controllers/ContractorDetailsControllerSpec.scala, test/views/ContractorDetailsViewSpec.scala
[SASS-4902](https://jira.tools.tax.service.gov.uk/browse/SASS-4902)
=> SASS-4902 fix accessibility issue #5749: Validation does not accommodate spaces

app/config/AppConfig.scala, app/utils/InYearUtil.scala, conf/application.conf, test/actions/ActionsProviderSpec.scala, test/actions/EndOfYearFilterActionSpec.scala, test/actions/InYearFilterActionSpec.scala, test/support/stubs/AppConfigStub.scala, test/utils/InYearUtilSpec.scala
=> update eoy toggle

app/views/ContractorSummaryView.scala.html, conf/messages, conf/messages.cy, test/views/ContractorSummaryViewSpec.scala
=> SASS-5119 - CIS helpline content change

build.sbt, project/build.properties, project/plugins.sbt, scalastyle-config.xml, scalastyle-test-config.xml
=> SASS-7027: Update Scala Dependencies

project/AppDependencies.scala
=> SASS-7277: upgrade play-frontend-hmrc-play

app/views/templates/helpers/DateInput.scala.html, app/views/templates/helpers/InputRadio.scala.html, app/views/templates/helpers/InputText.scala.html, build.sbt, conf/logback.xml, it/test/connectors/IncomeTaxUserDataConnectorSpec.scala, project/build.properties, project/plugins.sbt, test/support/ViewHelper.scala, test/support/builders/models/CISSourceBuilder.scala, test/support/builders/models/CisDeductionsBuilder.scala, test/support/builders/models/PeriodDataBuilder.scala
=> SASS-9201 | Fix error prefix text not being translated to welsh

conf/application.conf, it/test/support/IntegrationTest.scala
=> SASS-10499

app/actions/AuthorisedAction.scala, check.sh, test/actions/AuthorisedActionSpec.scala, test/support/mocks/MockAuthorisedAction.scala
=> [SASS-10772] Handle non-Auth exception and render ISE
